# Generated by Django 2.2.4 on 2019-08-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190718_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contents',
        ),
    ]
