# Docker-compose.yml file for kagxin/django_project_template project
version: "3"
services:
    mysql:
        image: mysql:5.6
        container_name: mysqldb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=toplist
        restart: always
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--default-time-zone=+8:00'
        ]

    redis:
        image: redis
        container_name: redisdb
        restart: always

    toplist:
        container_name: toplist_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9001:8000"
        environment:
            - mysqlhost=mysqldb
            - redishost=redisdb
        depends_on:
            - mysql
            - redis
        links:
            - "mysql:mysqldb"
            - "redis:redisdb"
        restart: always
