# Generated by Django 2.2.4 on 2019-08-10 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(1, '糗事百科'), (2, '知乎')], default=1, verbose_name='站点类型')),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('rank', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'entry',
                'unique_together': {('target', 'rank')},
            },
        ),
    ]
