# Generated by Django 2.2.4 on 2019-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
